<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>6c0ce55e-9304-44d0-93aa-d30836fb5f85</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\UrlShortener.ApiService\UrlShortener.ApiService.csproj" />
    <ProjectReference Include="..\UrlShortener.Web\UrlShortener.Web.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.2.1" />
  </ItemGroup>
</Project>
